# Generated by Django 2.1.5 on 2020-05-03 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 21, 33, 38, 74018), verbose_name='date published'),
        ),
    ]
