# Generated by Django 2.1.5 on 2020-04-28 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200428_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 17, 14, 5, 225501), verbose_name='date published'),
        ),
    ]
