# Generated by Django 2.1.5 on 2020-05-04 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200504_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 13, 2, 4, 782391), verbose_name='date published'),
        ),
    ]
