# Generated by Django 2.1.5 on 2020-04-29 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200429_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 12, 39, 30, 574107), verbose_name='date published'),
        ),
    ]
