# Generated by Django 2.1.5 on 2020-04-29 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200429_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 16, 12, 11, 115127), verbose_name='date published'),
        ),
    ]
