# Generated by Django 2.1.5 on 2020-04-30 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200429_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 15, 22, 54, 691463), verbose_name='date published'),
        ),
    ]
