# Generated by Django 2.1.5 on 2020-04-30 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200430_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 19, 38, 36, 370791), verbose_name='date published'),
        ),
    ]
