# Generated by Django 2.1.5 on 2020-05-01 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200430_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 17, 8, 23, 415073), verbose_name='date published'),
        ),
    ]
