# Generated by Django 2.1.5 on 2020-05-01 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200501_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 0, 16, 33, 625026), verbose_name='date published'),
        ),
    ]
