# Generated by Django 2.1.5 on 2020-05-06 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200504_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Categories', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 20, 41, 53, 136525), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Categories', verbose_name='category'),
        ),
    ]
