# Generated by Django 2.1.5 on 2020-05-01 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200502_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 2, 36, 35, 784585), verbose_name='date published'),
        ),
    ]
