# Generated by Django 2.1.5 on 2020-05-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200502_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='published',
        ),
    ]
