# Generated by Django 2.1.5 on 2020-05-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_products_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 3, 34, 0, 27196), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
