# Generated by Django 2.1.5 on 2020-05-02 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200502_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 16, 41, 49, 795877), verbose_name='date published'),
        ),
    ]
