# Generated by Django 2.1.5 on 2020-05-02 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200502_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 0, 27, 51, 109889), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
