# Generated by Django 2.1.5 on 2020-05-02 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200503_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 0, 30, 45, 547214), verbose_name='date published'),
        ),
    ]
