# Generated by Django 2.1.5 on 2020-05-02 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200503_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 0, 33, 38, 820199), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
