# Generated by Django 2.1.5 on 2020-05-02 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200503_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 1, 48, 196413), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
