# Generated by Django 2.1.5 on 2020-05-02 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200503_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 17, 53, 638399), verbose_name='date published'),
        ),
    ]
