# Generated by Django 2.1.5 on 2020-05-02 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200503_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 1, 27, 58, 751374), verbose_name='date published'),
        ),
    ]
